apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-sit
  name: test-sit
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32730
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: test-sit
  type: NodePort